### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by shenglintang** [Freelander/Elephant#15]
Error:(18, 1) A problem occurred evaluating project ':app'.
> Could not get unknown property 'CLIENT_ID' for ProductFlavor_Decorated{name=main, dimension=null, 
minSdkVersion=DefaultApiVersion{mApiLevel=15, mCodename='null'}, 
targetSdkVersion=DefaultApiVersion{mApiLevel=24, mCodename='null'},
 renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, 
 renderscriptSupportModeBlasEnabled=null, 
 renderscriptNdkModeEnabled=null, versionCode=5, versionName=1.0.2, 
 applicationId=com.jun.elephant, testApplicationId=null, testInstrumentationRunner=null, 
 testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, 
 signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={},
 mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, 
 mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.

**Comment by Freelander** [comment]
麻烦你看一下 issues 2 先，这里我已经给出解决的方法：https://github.com/Freelander/Elephant/issues/2
