### ISSUE TITLE
关于ptr-lib

### ISSUE THREAD

**Issue by fanturbo** [Freelander/Elephant#19]
想问下，项目里的ptr-lib是你在https://github.com/liaohuqiu/android-cube-app做了修改的对吗？并不只是简单的引用了这个项目？

**Comment by Freelander** [comment]
不是，我是直接使用这个库的 [地址](https://github.com/captainbupt/android-Ultra-Pull-To-Refresh-With-Load-More/blob/master/README-cn.md)，该库就是对[Ultra Pull To Refresh](https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh) 进行修改，使得其支持了上拉加载更多。

**Comment by fanturbo** [comment]
thanks!
