### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by namelin2** [Freelander/Elephant#2]
无法编译
![Uploading QQ图片20161019122427.png…]()

**Comment by namelin2** [comment]
Error:(18, 0) Could not get unknown property 'CLIENT_ID' for ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=15, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=24, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=3, versionName=1.0, applicationId=com.jun.elephant, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.
<a href="openFile:C:\Users\Arlen\Desktop\Elephant-master\app\build.gradle">Open File</a>

**Comment by bryanno1** [comment]
一样的问题。请问怎么解决。

**Comment by Freelander** [comment]
@namelin2 @bryan111 你们这个问题是因为还没有配置好 gradle.properties 文件里面的相关信息，文档上也有说明，下载完源码之后，需要复制 gradle.properties.example 更名为 gradle.properties 并编辑 里面的相关信息，文件里也有相对应注释。

**Comment by bryanno1** [comment]
@Freelander 已解决。感谢。

**Comment by sunnyxibei** [comment]
怎样获取CLIENT_ID呀？

**Comment by Freelander** [comment]
@sunnyxibei API_BASE_URL ，CLIENT_ID， CLIENT_SECRET 这三个需要单独跟 PHPHub 社区管理员申请要。

**Comment by Freelander** [comment]
@namelin2 @bryan111 @sunnyxibei API_BASE_URL ，CLIENT_ID， CLIENT_SECRET 这几个参数我已经更新代码配置线上测试环境的相对应的参数了，你们可以不用去向 PHPhub 管理员要了，另外 APi 文档可以到这帖子看看 https://laravel-china.org/topics/3097
