### ISSUE TITLE
网络请求失败，无数据

### ISSUE THREAD

**Issue by sushiwu** [Freelander/Elephant#7]
PHPHub已经开发了API，但是配置了 key 之后还是请求失败，请看下是我配置的不对吗？ 谢谢

CLIENT_ID=kHOugsx4dmcXwvVbmLkd
CLIENT_SECRET=PuuFCrF94MloSbSkxpwS
API_BASE_URL=https://staging.phphub.org/v1

**Comment by Freelander** [comment]
@returnight 这个配置没有错，你有没有下载我最新的代码？最新的代码这几个参数我已经给你们配置好了，只要将 gradle.properties.example 文件改名为 gradle.properties 导入 as 就可以使用了，有什么问题欢迎继续反馈。

**Comment by Freelander** [comment]
@returnight 喔喔！！我发现你什么问题了，API_BASE_URL 参数后面的链接地址最后应该还要加上 “ / ” ，具体请看我项目代码
