### ISSUE TITLE
版本24太高了，我换了低版本的，为什么显示找不到资源

### ISSUE THREAD

**Issue by yufan2014** [Freelander/Elephant#8]
Error:(226) No resource identifier found for attribute 'contentInsetStartWithNavigation' in package 'com.jun.elephant'

**Comment by Freelander** [comment]
因为这个属性在 Api 24 才有，如果你要降低版本，那你可以去有这个属性的地方删除掉，不过还是建议你支持版本 24 以上。

**Comment by yufan2014** [comment]
不是我不想用，是高版本运行装不到一般的手机上，显示版本太高，系统版本太低，5.0都运行不了，怎么破

**Comment by Freelander** [comment]
什么手机？按道理是不会出现这种情况，4.0 以上的版本我都已经运行过没有问题啊，5.0 系统更加不可能运行不了

**Comment by yufan2014** [comment]
不管什么样的手机，我试了模拟器，魅族，努比亚等等，都不行。This version of android studio is incompatible with the gradle version used.Try disabling the instant run出现这样的错误，我很头疼啊

**Comment by Freelander** [comment]
出现这个问题是你 Gradle 版本或者 As 版本跟我的不一致，你可以找到相对应的文件改成你的环境版本，或者升级跟我给出的版本，请仔细阅读 README文件我给出的环境要求。
